INFO 2022-08-03 20:27:08,256 - Started server process [82835]
INFO 2022-08-03 20:27:08,256 - Waiting for application startup.
INFO 2022-08-03 20:27:08,263 - Application startup complete.
INFO 2022-08-03 20:27:08,265 - Uvicorn running on http://127.0.0.1:5002 (Press CTRL+C to quit)
INFO 2022-08-03 20:27:18,406 - ('127.0.0.1', 61763) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:27:18,407 - connection open
ERROR 2022-08-03 20:27:19,765 - 使用者admin1  登入時間2022-08-03 20:27:19
INFO 2022-08-03 20:28:36,178 - connection closed
INFO 2022-08-03 20:28:36,500 - ('127.0.0.1', 61839) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:28:36,501 - connection open
ERROR 2022-08-03 20:28:36,735 - 使用者admin1  登入時間2022-08-03 20:28:36
INFO 2022-08-03 20:31:14,512 - connection closed
INFO 2022-08-03 20:31:15,176 - ('127.0.0.1', 62287) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:31:15,178 - connection open
ERROR 2022-08-03 20:31:15,478 - 使用者admin1  登入時間2022-08-03 20:31:15
INFO 2022-08-03 20:32:22,879 - connection closed
INFO 2022-08-03 20:32:23,233 - ('127.0.0.1', 62577) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:32:23,235 - connection open
ERROR 2022-08-03 20:32:23,536 - 使用者admin1  登入時間2022-08-03 20:32:23
INFO 2022-08-03 20:34:50,386 - ('127.0.0.1', 63209) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:34:50,391 - connection open
ERROR 2022-08-03 20:34:50,983 - 使用者personalBabysitter1  登入時間2022-08-03 20:34:50
INFO 2022-08-03 20:35:42,103 - ('127.0.0.1', 63453) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:35:42,104 - connection open
ERROR 2022-08-03 20:35:42,661 - 使用者personalBabysitter1  登入時間2022-08-03 20:35:42
ERROR 2022-08-03 20:36:11,506 - Task exception was never retrieved
future: <Task finished name='Task-163' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 133, in on_insert_banch_table
    await self.broadCast(label, sid)
  File "socketIo.py", line 198, in broadCast
    to = self.redisDB.selectManager(label[banch])['sid'],
KeyError: '保育組,'
INFO 2022-08-03 20:36:18,400 - connection closed
INFO 2022-08-03 20:36:18,659 - ('127.0.0.1', 63685) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:36:18,660 - connection open
ERROR 2022-08-03 20:36:18,810 - 使用者personalBabysitter1  登入時間2022-08-03 20:36:18
INFO 2022-08-03 20:36:25,848 - connection closed
INFO 2022-08-03 20:36:26,108 - ('127.0.0.1', 63744) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:36:26,110 - connection open
ERROR 2022-08-03 20:36:26,288 - 使用者personalBabysitter1  登入時間2022-08-03 20:36:26
INFO 2022-08-03 20:38:30,797 - connection closed
INFO 2022-08-03 20:38:31,222 - ('127.0.0.1', 64270) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:38:31,224 - connection open
ERROR 2022-08-03 20:38:31,533 - 使用者admin1  登入時間2022-08-03 20:38:31
INFO 2022-08-03 20:38:33,320 - connection closed
INFO 2022-08-03 20:38:33,598 - ('127.0.0.1', 64288) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:38:33,599 - connection open
ERROR 2022-08-03 20:38:33,819 - 使用者personalBabysitter1  登入時間2022-08-03 20:38:33
INFO 2022-08-03 20:38:35,780 - connection closed
INFO 2022-08-03 20:38:36,076 - ('127.0.0.1', 64302) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:38:36,076 - connection open
ERROR 2022-08-03 20:38:36,284 - 使用者personalBabysitter1  登入時間2022-08-03 20:38:36
INFO 2022-08-03 20:39:35,177 - connection closed
INFO 2022-08-03 20:39:35,441 - ('127.0.0.1', 64656) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:39:35,442 - connection open
ERROR 2022-08-03 20:39:35,605 - 使用者personalBabysitter1  登入時間2022-08-03 20:39:35
ERROR 2022-08-03 20:40:35,427 - Task exception was never retrieved
future: <Task finished name='Task-346' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 133, in on_insert_banch_table
    await self.broadCast(label, sid)
  File "socketIo.py", line 198, in broadCast
    to = self.redisDB.selectManager(label[banch])['sid'],
KeyError: '保育組,'
INFO 2022-08-03 20:40:42,529 - connection closed
INFO 2022-08-03 20:40:42,842 - ('127.0.0.1', 65007) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:40:42,843 - connection open
ERROR 2022-08-03 20:40:43,033 - 使用者personalBabysitter1  登入時間2022-08-03 20:40:43
INFO 2022-08-03 20:41:00,347 - connection closed
INFO 2022-08-03 20:42:41,226 - ('127.0.0.1', 49186) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:42:41,236 - connection open
ERROR 2022-08-03 20:42:41,461 - 使用者personalBabysitter1  登入時間2022-08-03 20:42:41
INFO 2022-08-03 20:42:44,776 - connection closed
INFO 2022-08-03 20:42:45,162 - ('127.0.0.1', 49208) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:42:45,163 - connection open
ERROR 2022-08-03 20:42:45,504 - 使用者personalBabysitter1  登入時間2022-08-03 20:42:45
INFO 2022-08-03 20:42:48,000 - connection closed
INFO 2022-08-03 20:42:48,356 - ('127.0.0.1', 49226) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:42:48,359 - connection open
ERROR 2022-08-03 20:42:48,600 - 使用者personalBabysitter1  登入時間2022-08-03 20:42:48
INFO 2022-08-03 20:42:50,995 - connection closed
INFO 2022-08-03 20:42:51,318 - ('127.0.0.1', 49249) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:42:51,319 - connection open
ERROR 2022-08-03 20:42:51,607 - 使用者admin1  登入時間2022-08-03 20:42:51
INFO 2022-08-03 20:43:06,872 - connection closed
INFO 2022-08-03 20:43:07,115 - ('127.0.0.1', 49399) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:43:07,116 - connection open
ERROR 2022-08-03 20:43:07,254 - 使用者personalBabysitter1  登入時間2022-08-03 20:43:07
INFO 2022-08-03 20:43:59,506 - connection closed
INFO 2022-08-03 20:43:59,833 - ('127.0.0.1', 49640) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:43:59,834 - connection open
ERROR 2022-08-03 20:44:00,067 - 使用者personalBabysitter1  登入時間2022-08-03 20:44:00
INFO 2022-08-03 20:44:02,924 - connection closed
INFO 2022-08-03 20:44:03,207 - ('127.0.0.1', 49669) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:44:03,208 - connection open
ERROR 2022-08-03 20:44:03,414 - 使用者admin1  登入時間2022-08-03 20:44:03
INFO 2022-08-03 20:44:23,059 - connection closed
INFO 2022-08-03 20:44:23,392 - ('127.0.0.1', 49787) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:44:23,393 - connection open
ERROR 2022-08-03 20:44:23,589 - 使用者personalBabysitter1  登入時間2022-08-03 20:44:23
INFO 2022-08-03 20:44:28,537 - connection closed
INFO 2022-08-03 20:44:28,842 - ('127.0.0.1', 49819) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:44:28,842 - connection open
ERROR 2022-08-03 20:44:29,006 - 使用者personalBabysitter1  登入時間2022-08-03 20:44:29
INFO 2022-08-03 20:44:30,863 - connection closed
INFO 2022-08-03 20:44:31,188 - ('127.0.0.1', 49840) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:44:31,189 - connection open
ERROR 2022-08-03 20:44:31,371 - 使用者admin1  登入時間2022-08-03 20:44:31
ERROR 2022-08-03 20:44:44,639 - Task exception was never retrieved
future: <Task finished name='Task-589' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 133, in on_insert_banch_table
    await self.broadCast(label, sid)
  File "socketIo.py", line 198, in broadCast
    to = self.redisDB.selectManager(label[banch])['sid'],
KeyError: '保育組,'
INFO 2022-08-03 20:55:51,176 - connection closed
INFO 2022-08-03 20:55:51,280 - connection closed
INFO 2022-08-03 20:55:51,285 - connection closed
INFO 2022-08-03 20:55:52,705 - ('127.0.0.1', 52688) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:55:52,712 - connection open
ERROR 2022-08-03 20:55:53,045 - 使用者personalBabysitter1  登入時間2022-08-03 20:55:53
INFO 2022-08-03 20:55:53,173 - ('127.0.0.1', 52693) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:55:53,174 - connection open
ERROR 2022-08-03 20:55:53,387 - 使用者personalBabysitter1  登入時間2022-08-03 20:55:53
INFO 2022-08-03 20:55:53,652 - ('127.0.0.1', 52703) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 20:55:53,653 - connection open
ERROR 2022-08-03 20:55:53,810 - 使用者admin1  登入時間2022-08-03 20:55:53
INFO 2022-08-03 21:06:49,086 - connection closed
INFO 2022-08-03 21:06:49,088 - connection closed
INFO 2022-08-03 21:06:49,091 - connection closed
INFO 2022-08-03 21:06:50,011 - ('127.0.0.1', 52723) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:06:50,012 - connection open
ERROR 2022-08-03 21:06:50,089 - 使用者personalBabysitter1  登入時間2022-08-03 21:06:50
INFO 2022-08-03 21:06:50,587 - ('127.0.0.1', 52728) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:06:50,588 - connection open
ERROR 2022-08-03 21:06:50,700 - 使用者personalBabysitter1  登入時間2022-08-03 21:06:50
INFO 2022-08-03 21:06:52,089 - ('127.0.0.1', 52741) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:06:52,090 - connection open
ERROR 2022-08-03 21:06:52,211 - 使用者admin1  登入時間2022-08-03 21:06:52
INFO 2022-08-03 21:24:16,885 - connection closed
INFO 2022-08-03 21:24:16,897 - connection closed
INFO 2022-08-03 21:24:16,898 - connection closed
INFO 2022-08-03 21:24:18,221 - ('127.0.0.1', 52930) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:24:18,222 - connection open
INFO 2022-08-03 21:24:18,247 - ('127.0.0.1', 52931) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:24:18,247 - connection open
ERROR 2022-08-03 21:24:18,544 - 使用者personalBabysitter1  登入時間2022-08-03 21:24:18
ERROR 2022-08-03 21:24:18,641 - 使用者admin1  登入時間2022-08-03 21:24:18
INFO 2022-08-03 21:24:19,745 - ('127.0.0.1', 52946) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:24:19,745 - connection open
ERROR 2022-08-03 21:24:19,917 - 使用者personalBabysitter1  登入時間2022-08-03 21:24:19
INFO 2022-08-03 21:29:17,309 - connection closed
INFO 2022-08-03 21:29:17,837 - ('127.0.0.1', 54214) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:29:17,841 - connection open
ERROR 2022-08-03 21:29:18,704 - 使用者personalBabysitter1  登入時間2022-08-03 21:29:18
INFO 2022-08-03 21:29:22,726 - connection closed
INFO 2022-08-03 21:29:23,079 - ('127.0.0.1', 54249) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:29:23,080 - connection open
ERROR 2022-08-03 21:29:23,395 - 使用者personalBabysitter1  登入時間2022-08-03 21:29:23
INFO 2022-08-03 21:32:23,342 - ('127.0.0.1', 55023) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:32:23,346 - connection open
ERROR 2022-08-03 21:32:23,539 - 使用者personalBabysitter1  登入時間2022-08-03 21:32:23
INFO 2022-08-03 21:32:23,854 - ('127.0.0.1', 55028) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:32:23,857 - connection open
ERROR 2022-08-03 21:32:23,993 - 使用者personalBabysitter1  登入時間2022-08-03 21:32:23
INFO 2022-08-03 21:32:24,027 - ('127.0.0.1', 55032) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:32:24,027 - connection open
ERROR 2022-08-03 21:32:24,163 - 使用者admin1  登入時間2022-08-03 21:32:24
INFO 2022-08-03 21:32:41,257 - ('127.0.0.1', 55116) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:32:41,260 - connection open
ERROR 2022-08-03 21:32:41,437 - 使用者personalBabysitter1  登入時間2022-08-03 21:32:41
INFO 2022-08-03 21:32:41,895 - ('127.0.0.1', 55125) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:32:41,899 - connection open
INFO 2022-08-03 21:32:41,916 - ('127.0.0.1', 55126) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:32:41,917 - connection open
ERROR 2022-08-03 21:32:42,156 - 使用者admin1  登入時間2022-08-03 21:32:42
ERROR 2022-08-03 21:32:42,264 - 使用者personalBabysitter1  登入時間2022-08-03 21:32:42
INFO 2022-08-03 21:36:10,864 - ('127.0.0.1', 56044) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:36:10,869 - connection open
ERROR 2022-08-03 21:36:10,998 - 使用者admin1  登入時間2022-08-03 21:36:10
INFO 2022-08-03 21:36:54,119 - ('127.0.0.1', 56232) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:36:54,121 - connection open
ERROR 2022-08-03 21:36:54,285 - 使用者admin1  登入時間2022-08-03 21:36:54
INFO 2022-08-03 21:37:13,086 - ('127.0.0.1', 56321) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:13,092 - connection open
ERROR 2022-08-03 21:37:13,324 - 使用者personalBabysitter1  登入時間2022-08-03 21:37:13
INFO 2022-08-03 21:37:13,880 - ('127.0.0.1', 56328) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:13,883 - connection open
ERROR 2022-08-03 21:37:14,048 - 使用者admin1  登入時間2022-08-03 21:37:14
INFO 2022-08-03 21:37:14,050 - ('127.0.0.1', 56332) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:14,050 - connection open
ERROR 2022-08-03 21:37:14,176 - 使用者personalBabysitter1  登入時間2022-08-03 21:37:14
INFO 2022-08-03 21:37:29,741 - ('127.0.0.1', 56405) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:29,743 - connection open
INFO 2022-08-03 21:37:29,869 - ('127.0.0.1', 56406) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:29,873 - connection open
INFO 2022-08-03 21:37:29,914 - ('127.0.0.1', 56407) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:29,916 - connection open
ERROR 2022-08-03 21:37:30,311 - 使用者personalBabysitter1  登入時間2022-08-03 21:37:30
ERROR 2022-08-03 21:37:30,421 - 使用者personalBabysitter1  登入時間2022-08-03 21:37:30
ERROR 2022-08-03 21:37:30,501 - 使用者admin1  登入時間2022-08-03 21:37:30
INFO 2022-08-03 21:37:36,135 - ('127.0.0.1', 56448) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:36,142 - connection open
ERROR 2022-08-03 21:37:36,294 - 使用者personalBabysitter1  登入時間2022-08-03 21:37:36
INFO 2022-08-03 21:37:36,818 - ('127.0.0.1', 56456) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:36,819 - connection open
INFO 2022-08-03 21:37:36,833 - ('127.0.0.1', 56457) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:37:36,834 - connection open
ERROR 2022-08-03 21:37:37,029 - 使用者admin1  登入時間2022-08-03 21:37:37
ERROR 2022-08-03 21:37:37,091 - 使用者personalBabysitter1  登入時間2022-08-03 21:37:37
INFO 2022-08-03 21:39:06,255 - connection closed
INFO 2022-08-03 21:39:06,271 - connection closed
INFO 2022-08-03 21:39:06,272 - connection closed
INFO 2022-08-03 21:39:06,274 - connection closed
INFO 2022-08-03 21:39:06,276 - connection closed
INFO 2022-08-03 21:39:06,279 - connection closed
INFO 2022-08-03 21:39:06,735 - ('127.0.0.1', 56848) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:39:06,737 - connection open
ERROR 2022-08-03 21:39:07,397 - 使用者personalBabysitter1  登入時間2022-08-03 21:39:07
INFO 2022-08-03 21:39:08,627 - connection closed
INFO 2022-08-03 21:39:08,633 - connection closed
INFO 2022-08-03 21:39:08,637 - connection closed
INFO 2022-08-03 21:39:08,639 - connection closed
INFO 2022-08-03 21:39:08,642 - connection closed
INFO 2022-08-03 21:39:08,643 - connection closed
INFO 2022-08-03 21:39:09,167 - ('127.0.0.1', 56863) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:39:09,169 - connection open
ERROR 2022-08-03 21:39:09,500 - 使用者personalBabysitter1  登入時間2022-08-03 21:39:09
INFO 2022-08-03 21:39:10,857 - connection closed
INFO 2022-08-03 21:39:10,860 - connection closed
INFO 2022-08-03 21:39:10,867 - connection closed
INFO 2022-08-03 21:39:10,868 - connection closed
INFO 2022-08-03 21:39:10,869 - connection closed
INFO 2022-08-03 21:39:10,871 - connection closed
INFO 2022-08-03 21:39:10,872 - connection closed
INFO 2022-08-03 21:39:10,873 - connection closed
INFO 2022-08-03 21:39:11,282 - ('127.0.0.1', 56888) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:39:11,283 - connection open
ERROR 2022-08-03 21:39:11,680 - 使用者admin1  登入時間2022-08-03 21:39:11
INFO 2022-08-03 21:39:29,818 - connection closed
INFO 2022-08-03 21:39:30,255 - ('127.0.0.1', 56984) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:39:30,256 - connection open
ERROR 2022-08-03 21:39:30,646 - 使用者admin1  登入時間2022-08-03 21:39:30
INFO 2022-08-03 21:39:31,891 - connection closed
INFO 2022-08-03 21:39:32,333 - ('127.0.0.1', 57006) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:39:32,338 - connection open
ERROR 2022-08-03 21:39:32,556 - 使用者personalBabysitter1  登入時間2022-08-03 21:39:32
INFO 2022-08-03 21:39:34,029 - connection closed
INFO 2022-08-03 21:39:34,358 - ('127.0.0.1', 57020) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:39:34,359 - connection open
ERROR 2022-08-03 21:39:34,675 - 使用者personalBabysitter1  登入時間2022-08-03 21:39:34
INFO 2022-08-03 21:39:50,382 - connection closed
INFO 2022-08-03 21:39:50,647 - ('127.0.0.1', 57167) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:39:50,649 - connection open
ERROR 2022-08-03 21:39:50,833 - 使用者personalBabysitter1  登入時間2022-08-03 21:39:50
ERROR 2022-08-03 21:39:56,939 - Task exception was never retrieved
future: <Task finished name='Task-2104' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 133, in on_insert_banch_table
    await self.broadCast(label, sid)
  File "socketIo.py", line 198, in broadCast
    to = self.redisDB.selectManager(label[banch])['sid'],
KeyError: '保育組,'
INFO 2022-08-03 21:41:36,770 - connection closed
INFO 2022-08-03 21:41:37,110 - ('127.0.0.1', 57682) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:41:37,111 - connection open
ERROR 2022-08-03 21:41:37,325 - 使用者personalBabysitter1  登入時間2022-08-03 21:41:37
INFO 2022-08-03 21:43:02,231 - connection closed
INFO 2022-08-03 21:43:02,547 - ('127.0.0.1', 58067) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:43:02,548 - connection open
ERROR 2022-08-03 21:43:02,839 - 使用者personalBabysitter1  登入時間2022-08-03 21:43:02
INFO 2022-08-03 21:43:18,407 - connection closed
INFO 2022-08-03 21:43:22,386 - ('127.0.0.1', 58229) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:43:22,387 - connection open
ERROR 2022-08-03 21:43:22,476 - 使用者personalBabysitter1  登入時間2022-08-03 21:43:22
INFO 2022-08-03 21:43:32,956 - connection closed
INFO 2022-08-03 21:43:33,298 - ('127.0.0.1', 58306) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:43:33,300 - connection open
ERROR 2022-08-03 21:43:33,523 - 使用者personalBabysitter1  登入時間2022-08-03 21:43:33
INFO 2022-08-03 21:45:50,633 - connection closed
INFO 2022-08-03 21:45:51,209 - ('127.0.0.1', 58890) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:45:51,212 - connection open
ERROR 2022-08-03 21:45:51,722 - 使用者admin1  登入時間2022-08-03 21:45:51
INFO 2022-08-03 21:45:52,661 - connection closed
INFO 2022-08-03 21:45:52,954 - ('127.0.0.1', 58906) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:45:52,955 - connection open
ERROR 2022-08-03 21:45:53,127 - 使用者personalBabysitter1  登入時間2022-08-03 21:45:53
INFO 2022-08-03 21:45:54,962 - connection closed
INFO 2022-08-03 21:45:55,265 - ('127.0.0.1', 58921) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:45:55,265 - connection open
ERROR 2022-08-03 21:45:55,527 - 使用者personalBabysitter1  登入時間2022-08-03 21:45:55
ERROR 2022-08-03 21:46:00,712 - Task exception was never retrieved
future: <Task finished name='Task-2344' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 133, in on_insert_banch_table
    await self.broadCast(label, sid)
  File "socketIo.py", line 198, in broadCast
    to = self.redisDB.selectManager(label[banch])['sid'],
KeyError: '保育組,'
INFO 2022-08-03 21:46:07,054 - connection closed
INFO 2022-08-03 21:48:23,070 - connection closed
INFO 2022-08-03 21:50:01,172 - ('127.0.0.1', 60046) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:50:01,174 - connection open
ERROR 2022-08-03 21:50:01,584 - 使用者personalBabysitter1  登入時間2022-08-03 21:50:01
INFO 2022-08-03 21:50:23,763 - ('127.0.0.1', 60211) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:50:23,764 - connection open
ERROR 2022-08-03 21:50:24,261 - 使用者managerBabysitter  登入時間2022-08-03 21:50:24
INFO 2022-08-03 21:50:26,865 - connection closed
INFO 2022-08-03 21:50:27,165 - ('127.0.0.1', 60249) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:50:27,166 - connection open
ERROR 2022-08-03 21:50:27,333 - 使用者managerBabysitter  登入時間2022-08-03 21:50:27
INFO 2022-08-03 21:50:29,430 - connection closed
INFO 2022-08-03 21:50:29,734 - ('127.0.0.1', 60274) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:50:29,735 - connection open
ERROR 2022-08-03 21:50:29,919 - 使用者admin1  登入時間2022-08-03 21:50:29
ERROR 2022-08-03 21:51:27,392 - Task exception was never retrieved
future: <Task finished name='Task-2481' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 133, in on_insert_banch_table
    await self.broadCast(label, sid)
  File "socketIo.py", line 198, in broadCast
    to = self.redisDB.selectManager(label[banch])['sid'],
KeyError: '保育組,'
INFO 2022-08-03 21:53:38,788 - connection closed
INFO 2022-08-03 21:53:39,148 - ('127.0.0.1', 61400) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:53:39,149 - connection open
ERROR 2022-08-03 21:53:39,523 - 使用者managerBabysitter  登入時間2022-08-03 21:53:39
INFO 2022-08-03 21:53:40,728 - connection closed
INFO 2022-08-03 21:53:41,012 - ('127.0.0.1', 61414) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:53:41,013 - connection open
ERROR 2022-08-03 21:53:41,223 - 使用者managerBabysitter  登入時間2022-08-03 21:53:41
INFO 2022-08-03 21:53:42,702 - connection closed
INFO 2022-08-03 21:53:43,242 - ('127.0.0.1', 61432) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:53:43,243 - connection open
ERROR 2022-08-03 21:53:43,617 - 使用者admin1  登入時間2022-08-03 21:53:43
INFO 2022-08-03 21:53:45,196 - connection closed
INFO 2022-08-03 21:53:45,637 - ('127.0.0.1', 61466) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:53:45,640 - connection open
ERROR 2022-08-03 21:53:46,547 - 使用者personalBabysitter1  登入時間2022-08-03 21:53:46
INFO 2022-08-03 21:53:58,418 - connection closed
INFO 2022-08-03 21:53:58,688 - ('127.0.0.1', 61596) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:53:58,690 - connection open
ERROR 2022-08-03 21:53:58,857 - 使用者managerBabysitter  登入時間2022-08-03 21:53:58
INFO 2022-08-03 21:54:22,814 - connection closed
INFO 2022-08-03 21:54:23,249 - ('127.0.0.1', 61714) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:54:23,251 - connection open
ERROR 2022-08-03 21:54:23,690 - 使用者managerBabysitter  登入時間2022-08-03 21:54:23
INFO 2022-08-03 21:54:26,766 - connection closed
INFO 2022-08-03 21:54:27,094 - ('127.0.0.1', 61736) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:54:27,099 - connection open
ERROR 2022-08-03 21:54:27,431 - 使用者personalBabysitter1  登入時間2022-08-03 21:54:27
INFO 2022-08-03 21:54:28,849 - connection closed
INFO 2022-08-03 21:54:29,170 - ('127.0.0.1', 61758) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:54:29,172 - connection open
ERROR 2022-08-03 21:54:29,435 - 使用者admin1  登入時間2022-08-03 21:54:29
ERROR 2022-08-03 21:54:33,142 - Task exception was never retrieved
future: <Task finished name='Task-2660' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 133, in on_insert_banch_table
    await self.broadCast(label, sid)
  File "socketIo.py", line 198, in broadCast
    to = self.redisDB.selectManager(label[banch])['sid'],
KeyError: '保育組,'
INFO 2022-08-03 21:54:34,725 - connection closed
INFO 2022-08-03 21:54:35,021 - ('127.0.0.1', 61851) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:54:35,022 - connection open
ERROR 2022-08-03 21:54:35,233 - 使用者managerBabysitter  登入時間2022-08-03 21:54:35
INFO 2022-08-03 21:54:54,031 - connection closed
INFO 2022-08-03 21:54:54,280 - ('127.0.0.1', 62053) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:54:54,281 - connection open
ERROR 2022-08-03 21:54:54,439 - 使用者managerBabysitter  登入時間2022-08-03 21:54:54
INFO 2022-08-03 21:56:00,105 - connection closed
INFO 2022-08-03 21:56:00,377 - ('127.0.0.1', 62396) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:56:00,382 - connection open
ERROR 2022-08-03 21:56:00,524 - 使用者managerBabysitter  登入時間2022-08-03 21:56:00
INFO 2022-08-03 21:56:05,563 - connection closed
INFO 2022-08-03 21:56:05,898 - ('127.0.0.1', 62442) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 21:56:05,898 - connection open
ERROR 2022-08-03 21:56:06,080 - 使用者personalBabysitter1  登入時間2022-08-03 21:56:06
ERROR 2022-08-03 22:03:20,342 - Task exception was never retrieved
future: <Task finished name='Task-2916' coro=<AsyncServer._handle_event_internal() done, defined at /Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py:521> exception=KeyError('保育組,er')>
Traceback (most recent call last):
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 523, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_server.py", line 568, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/siou/.pyenv/versions/3.8.13/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "socketIo.py", line 173, in on_updata_performance_table
    label = {'user': data[3], 'banch': [data[-1]], 'permession': select_banch(data[3]), 'event': 'updata_performance_table'}
  File "socketIo.py", line 198, in broadCast
    await self.emit(
KeyError: '保育組,er'
INFO 2022-08-03 22:03:24,425 - connection closed
INFO 2022-08-03 22:03:25,018 - ('127.0.0.1', 64336) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 22:03:25,025 - connection open
ERROR 2022-08-03 22:03:25,330 - 使用者admin1  登入時間2022-08-03 22:03:25
INFO 2022-08-03 22:03:28,914 - connection closed
INFO 2022-08-03 22:03:29,350 - ('127.0.0.1', 64383) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 22:03:29,351 - connection open
ERROR 2022-08-03 22:03:29,668 - 使用者personalBabysitter1  登入時間2022-08-03 22:03:29
INFO 2022-08-03 22:04:17,410 - connection closed
INFO 2022-08-03 22:04:18,491 - connection closed
INFO 2022-08-03 22:05:48,576 - connection closed
INFO 2022-08-03 22:05:48,939 - ('127.0.0.1', 65024) - "WebSocket /socket.io/" [accepted]
INFO 2022-08-03 22:05:48,940 - connection open
ERROR 2022-08-03 22:05:49,238 - 使用者admin1  登入時間2022-08-03 22:05:49
INFO 2022-08-03 22:05:56,341 - connection closed
INFO 2022-08-03 22:06:05,607 - Shutting down
INFO 2022-08-03 22:06:05,710 - Waiting for application shutdown.
INFO 2022-08-03 22:06:05,713 - Application shutdown complete.
INFO 2022-08-03 22:06:05,713 - Finished server process [82835]
